python test.py --dataset ffhq --model vcn --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ../FocalNet/checkpoints/ffhq-vcn_lite-w_semantics --save_intermediate 0 --random_mask 0 --test_num 100
# python test.py --dataset ffhq --model vcn --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ../FocalNet/checkpoints/ffhq-vcn_lite --save_intermediate 0 --random_mask 0 --test_num 4
#python test_bce_mask.py --dataset ffhq --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite --mode slient --use_blend 0 --random_mask 0 --test_num 2000
#python test_bce_mask.py --dataset places2 --model vcn_lite --data_file /mnt/backup/project/yiwang/download/val_large.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/ImageNet/val/val.txt --load_model_dir ./checkpoints/places2-vcn_lite-pretrain --mode slient --random_mask 0 --test_num 4000
#python test.py --dataset places2 --model vcn_lite --data_file /mnt/backup/project/yiwang/download/val_large.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/ImageNet/val/val.txt --load_model_dir ./checkpoints/places2-vcn_lite --random_mask 0 --test_num 600
#python test.py --dataset places2 --model vcn_lite --data_file /mnt/backup/project/yiwang/download/val_large.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/ImageNet/val/val.txt --load_model_dir ./checkpoints/places2-vcn_lite-tune2 --random_mask 0 --test_num 4000
#python test.py --dataset places2 --model vcn_lite --data_file /mnt/backup/project/yiwang/download/val_large.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/ImageNet/val/val.txt --load_model_dir ./checkpoints/places2-vcn_lite-tune3 --random_mask 0 --test_num 4000
#python test.py --dataset ffhq-RM --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite-RM --embrace 1 --save_intermediate 0 --random_mask 0 --test_num 2000
#python test_bce_mask.py --dataset ffhq-RM --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite-RM-pretrain --embrace 1 --mode slient --use_blend 0 --random_mask 0 --test_num 2000
#python test.py --dataset ffhq --model vcn_lite_c --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/20190516-200257_vcn_lite_c_ffhq-blind_b4_s256x256_gc32_dc64_randmask-stroke --random_mask 0 --test_num 600
#python test.py --dataset imagenet --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ImageNet/val/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/val_large.txt --load_model_dir ./checkpoints/imagenet-vcn_lite-pretrain --random_mask 0 --test_num 4000
#python test_bce_mask.py --dataset imagenet --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ImageNet/val/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/val_large.txt --load_model_dir ./checkpoints/20190507-223754_vcn_lite_imagenet-blind_b4_s256x256_gc32_dc64_randmask-stroke  --mode slient --random_mask 0 --test_num 4000
#python test.py --dataset imagenet --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ImageNet/val/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/val_large.txt --load_model_dir ./checkpoints/20190507-223754_vcn_lite_imagenet-blind_b4_s256x256_gc32_dc64_randmask-stroke --random_mask 0 --test_num 600
#python test.py --dataset wallpaint --model vcn_lite --data_file /mnt/backup/project/yiwang/download/wallpainting_val/val.txt --use_noise 0 --data_noise /mnt/backup/project/yiwang/download/val_large.txt --load_model_dir ./checkpoints/20190511-134958_vcn_lite_wallpaint-blind_b4_s256x256_gc32_dc64_randmask-stroke --save_intermediate 1 --random_mask 0
#python test.py --dataset ffhq --model vcn_lite_c --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/20190518-003412_vcn_lite_c_ffhq-blind_b4_s256x256_gc32_dc64_randmask-stroke --save_intermediate 0 --random_mask 0 --test_num 600
#python test_bce_mask.py --dataset ffhq --model vcn_lite_c --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/20190518-003412_vcn_lite_c_ffhq-blind_b4_s256x256_gc32_dc64_randmask-stroke --mode slient --use_blend 0 --random_mask 0 --test_num 2000
#python test_bce_mask.py --dataset ffhq --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite-w_semantics --mode slient --use_blend 0 --random_mask 0 --test_num 2000
#python test.py --dataset ffhq --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite --save_intermediate 0 --random_mask 0 --test_num 600
#python remove_mask.py --dataset removaMask --model vcn_lite --data_file ./man_mask --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite-w_semantics --save_intermediate 0 --random_mask 0
#python remove_mask.py --dataset removaMask --model vcn_lite --data_file ./man_mask --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite-w_semantics --save_intermediate 0 --use_cn 0 --random_mask 0
#python remove_mask.py --dataset removaMask --model vcn_lite --data_file ./man_mask --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite --save_intermediate 0 --random_mask 0
#python remove_mask.py --dataset removaMask --model vcn_lite --data_file ./man_mask --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite --save_intermediate 0 --use_cn 0 --random_mask 0
#python remove_mask.py --dataset oldPic --model vcn_lite --data_file ./old-pic --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/20190517-232625_vcn_lite_portrait_b1_s640x480_gc32_dc64_randmask-stroke_pretrain --save_intermediate 0 --img_shapes 640,480 --random_mask 0
#python test.py --dataset ffhq --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/ffhq-vcn_lite-w_semantics --save_intermediate 0 --random_mask 0 --rho 1.0 --test_num 50
# python test.py --dataset ffhq --model vcn_lite --data_file /mnt/backup/project/yiwang/download/ffhq-256/val.txt --use_noise 1 --data_noise /mnt/backup/project/yiwang/download/celeba_hd_256/val.txt --load_model_dir ./checkpoints/20190507-223754_vcn_lite_imagenet-blind_b4_s256x256_gc32_dc64_randmask-stroke --save_intermediate 0 --random_mask 0 --test_num 50
