# ffhq
python train.py --dataset ffhq-blind --model vcn --gpu_ids 0 --data_file ./ffhq-256/train.txt --data_noise ./ImageNet/train/train.txt --data_noise_aux ./celeba_hd_256/train.txt --mask_type stroke --train_spe 1000 --batch_size 12 --img_shapes 256,256 --use_cn 1 --phase acc --lr 1e-4 --pretrain_network --max_iters 160000
#python train.py --dataset ffhq-blind --model vcn --gpu_ids 0 --data_file ./ffhq-256/train.txt --data_noise ./ImageNet/train/train.txt --data_noise_aux ./celeba_hd_256/train.txt --pretrain_network --load_model_dir checkpoints/20190428-022052_vcn_lite_ffhq-blind_b4_s256x256_gc32_dc64_randmask-stroke --mask_type stroke --train_spe 1000 --batch_size 16 --img_shapes 256,256 --use_cn 1 --phase acc --lr 1e-4 --max_iters 160000
#python train.py --dataset ffhq-blind --model vcn --gpu_ids 0 --data_file ./ffhq-256/train.txt --data_noise ./ImageNet/train/train.txt --data_noise_aux ./celeba_hd_256/train.txt --pretrain_network --load_model_dir checkpoints/20190429-233716_vcn_lite_ffhq-blind_b16_s256x256_gc32_dc64_randmask-stroke_pretrain --mask_type stroke --train_spe 1000 --batch_size 4 --img_shapes 256,256 --use_cn 1 --use_mrf 1 --phase tune --max_iters 160000
# places2, 256p
#python train.py --dataset places2-blind --model vcn --gpu_ids 0 --data_file places2_large_train.txt --data_noise ./ImageNet/train/keys.txt --pretrain_network 0 --load_model_dir checkpoints/xxx --mask_type stroke --train_spe 1000 --batch_size 4 --img_shapes 256,256 --use_cn 1 --use_mrf 1 --phase tune --max_iters 320000
#python train.py --dataset places2-blind --model vcn --gpu_ids 0 --data_file places2_large_train.txt --data_noise ./ImageNet/train/keys.txt --pretrain_network --load_model_dir checkpoints/xxx --mask_type stroke --train_spe 1000 --batch_size 4 --img_shapes 256,256 --use_cn 1 --use_mrf 1 --semantic_loss_alpha 1e-5 --mrf_alpha 0.2 --phase tune --max_iters 320000
# places2, 512p
#python train.py --dataset places2-blind --model vcn --gpu_ids 0 --data_file places2_large_train.txt --data_noise ./ImageNet/train/keys.txt --pretrain_network --load_model_dir checkpoints/xxx --mask_type rect --mask_shapes 128,128 --train_spe 1000 --batch_size 2 --use_cn 1 --rho 0.5 --use_mrf 1 --lr 1e-4 --img_shapes 512,512 --max_iters 160000
#python train.py --dataset places2-blind --model vcn --gpu_ids 0 --data_file places2_large_train.txt --data_noise ./ImageNet/train/keys.txt --pretrain_network --load_model_dir checkpoints/xxx --mask_type rect --mask_shapes 128,128 --train_spe 1000 --batch_size 2 --use_cn 1 --rho 0.5 --use_mrf 1 --mrf_alpha 0.5 --l1_loss_alpha 3.0 --semantic_loss_alpha 0.00015 --lr 1e-4 --img_shapes 512,512 --d_cnum 128 --max_iters 160000
# raindrop
#python train.py --dataset rain --model vcn_lite --gpu_ids 0 --data_file rain/train/gt --data_noise rain/train/data --pretrain_network 1 --load_model_dir checkpoints/vcn-rain-pretrain --mask_type stroke --train_spe 1000 --batch_size 1 --use_cn 1 --use_mrf 1 --rho 0.2 --lr 1e-5 --semantic_loss_alpha 0 --img_shapes 480,720 --max_iters 80000 --paired 1